
/* Generated by Interface Builder */

#import	"TileCountManager.h"
#import	"GameCoordinator.h"

#import "GameInterface.h"

extern "C" {
#import	<assert.h>
}


@implementation GameInterface
{
    GameCoordinator     *gameCoordinator;
    TileCountManager    *tileCountManager;
    // This flag is used to prevent draw messages
    //    from being sent to the C++ object before
    //    the application has finished initializing.
    BOOL            application_initialized;
}

- init {

	self = [ super init ];
	
	gameCoordinator		= NULL;
	tileCountManager	= NULL;
	
	return self;
}



- appDidInit:sender {


	assert( tileCountView );
	assert( gameBoardView );
	
	tileCountManager = new TileCountManager( tileCountView );
	gameCoordinator = new GameCoordinator( gameBoardView, tileCountManager );
	
	application_initialized = YES;
	
	[ tileCountView display ];
	[ gameBoardView display ];

	return self;
}


- (void)undoClick:sender {


	(( GameCoordinator* )gameCoordinator )->undoClick();
}


- (void)helpClick:sender {

	(( GameCoordinator* )gameCoordinator )->helpClick();

}


- (void)againClick:sender {


	(( GameCoordinator* )gameCoordinator )->againClick();

}

- (void)newClick:sender {


	(( GameCoordinator* )gameCoordinator )->newClick();

}


- (void)gameBoardDraw {


	if( application_initialized )
		(( GameCoordinator* )gameCoordinator )->drawImage();
}


- (void)tileCountDraw {


	if( application_initialized )
		(( TileCountManager* )tileCountManager )->drawImage();
}


- (void)click:(NSPoint)aPoint {


	(( GameCoordinator* )gameCoordinator )->click( aPoint );
	
}


- (void)doubleClick:(NSPoint)aPoint {


	(( GameCoordinator* )gameCoordinator )->doubleClick( aPoint );

}


@end
