
/* Generated by Interface Builder */

/*
 * This object is a view where the game's tiles are displayed.
 *	It is commonly referenced as the Game Board.
 *
 * This object has only one method, drawSelf::.  In this method
 *	the view is painted white and the interface object is
 *	instructed to composite the game tiles.
 *
 $Author$
 $Header$
 *
 $Log$
 */


#import "InterfaceView.h"

@interface GameBoardView:InterfaceView {

}


												// As a subclass of Responder, this object
												//	overrides the mouseDown: method such
												//	that click: and doubleClick: methods
												//	can be sent to the interface object.
- mouseDown:( NXEvent* )theEvent;
												// This object paints itself which and 
												//	informs the interface object to draw
												//	the tiles.
- drawSelf:(const NXRect *)rects :(int)rectCount;


@end
