
/* Generated by Interface Builder */

#import "InterfaceView.h"

@implementation InterfaceView


- (instancetype)initWithFrame:(NSRect)frameRect {


	self = [ super initWithFrame:frameRect ];

	return self;
}

@end
