
/* Generated by Interface Builder */

/*
 * An interface view is simple a base class for
 *	Objective-C views that interface with the Game Interface
 *	object.
 *
 * The sole purpose of this object is to hold a instance
 *	pointer to the Game Interface object.
 *
 *
 $Author$
 $Header$
 *
 $Log$
 */


#import <AppKit/NSView.h>

@class GameInterface;

@interface InterfaceView:NSView {

	//! This is the Game Interface
	//! object.
    IBOutlet GameInterface	*gameInterface;
}

//! Sets up some additional View
//! defaults.
- (instancetype)initWithFrame:(NSRect)frameRect;


@end
