
/* Generated by Interface Builder */

#import "InterfaceView.h"

@implementation InterfaceView


- initFrame:( const NXRect * )frameRect {


	self = [ super initFrame:frameRect ];

	return self;
}

@end
