
/* Generated by Interface Builder */

/*
 *
 $Author$
 $Header$
 *
 $Log$
 */
 

#import "TileCountView.h"
#import	"GameInterface.h"
#import <Cocoa/Cocoa.h>
#include <assert.h>


@implementation TileCountView

- (void)drawRect:(NSRect)dirtyRect
{
	assert(gameInterface);
	
	[gameInterface tileCountDraw];
}

@end
