
/* Generated by Interface Builder */

/*
 *
 $Author$
 $Header$
 *
 $Log$
 */
 

#import "TileCountView.h"
#import	"GameInterface.h"
#import <Cocoa/Cocoa.h>

#import	<assert.h>


@implementation TileCountView


- (void)drawRect:(NSRect)dirtyRect
{
	
	assert( gameInterface );
	
//	PSsetgray( NX_WHITE );
//	NXRectFillList( rects, rectCount );
	[( GameInterface* )gameInterface tileCountDraw ];
}


@end
