
/* Generated by Interface Builder */

/*
 *
 $Author$
 $Header$
 *
 $Log$
 */
 

#import "TileCountView.h"
#import	"GameInterface.h"
#import <appkit/graphics.h>
#import	<dpsclient/psops.h>

#import	<assert.h>


@implementation TileCountView


- drawSelf:(const NXRect *)rects :(int)rectCount {

	
	assert( gameInterface );
	
//	PSsetgray( NX_WHITE );
//	NXRectFillList( rects, rectCount );
	[( GameInterface* )gameInterface tileCountDraw ];
	
	return self;
}


@end
