
/* Generated by Interface Builder */

/*
 * This object is used to display the
 *	number of tiles remaining in the game.
 *
 * This object has only one method, drawSelf::.  In this method
 *	the view is painted white and the interface object is
 *	instructed to composite the number tiles.
 *
 $Author$
 $Header$
 *
 $Log$
 */

#import "InterfaceView.h"

@interface TileCountView:InterfaceView {

}


- drawSelf:(const NXRect *)rects :(int)rectCount;


@end
